spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345
    url: jdbc:mysql://101.132.103.204:3306/kitc?characterEncoding=utf-8&useSSL=false
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  jpa:
      #show-sql: true
      database: mysql
  #jackson:
      #default-property-inclusion: non_null
server:
  servlet:
    context-path: /kit


wechat:
  miniapp:
    configs:
      appid: wx5b245d22b7f87928
      secret: 8aedd83f16b754ed6fad79ad2b1f76fb
      token: nhz
      aesKey: nhz
      msgDataFormat: JSON
    pay:
      appId: wx5b245d22b7f87928
      mchId: 1483469312
      mchKey: 06C56A89949D617xxxxxxxxxxx
      keyPath: /var/weixin_cert/h5.p12
      notifyUrl: http://sell.natapp4.cc/sell/pay/notify